"""Add text index to Questions

Revision ID: 25c517b53bdc
Revises: deb53c5f1d07
Create Date: 2020-12-25 02:29:00.085273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25c517b53bdc'
down_revision = 'deb53c5f1d07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
