"""Add indexed_text to Questions

Revision ID: 6c70d1cff597
Revises: 25c517b53bdc
Create Date: 2020-12-25 02:31:24.486629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c70d1cff597'
down_revision = '25c517b53bdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('indexed_text', sa.UnicodeText(), nullable=True))
    op.drop_index('text_index', table_name='questions')
    op.create_index('text_index', 'questions', ['indexed_text'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('text_index', table_name='questions')
    op.create_index('text_index', 'questions', ['text'], unique=False)
    op.drop_column('questions', 'indexed_text')
    # ### end Alembic commands ###
